CREATE SCHEMA IF NOT EXISTS `netteTest` DEFAULT CHARACTER SET utf8 ;
USE `netteTest` ;

DROP TABLE IF EXISTS `netteTest` . `User`;
CREATE TABLE IF NOT EXISTS `netteTest` . `User` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`NAME` VARCHAR(45) NOT NULL,
	`SURNAME` VARCHAR(45) NOT NULL,
	`EMAIL` VARCHAR(45) NOT NULL,
	`HTML_TEXT` LONGTEXT NOT NULL,
	`CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(`ID`))
	ENGINE = InnoDB;

DROP TABLE IF EXISTS `netteTest` . `Article`;
CREATE TABLE IF NOT EXISTS `netteTest` . `Article` (
	`ID` INT NOT NULL AUTO_INCREMENT,
	`ID_USER` INT NOT NULL,
	`TITLE`	VARCHAR(45) NOT NULL,
	`TOPIC`	VARCHAR(45) NOT NULL,
	`CONTENT`	LONGTEXT NOT NULL,
	`CREATED` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (`ID`),
	CONSTRAINT	`FK_USER_ID` 
		FOREIGN KEY(`ID_USER`)
		REFERENCES `User` (`ID`))
	ENGINE = InnoDB;
